version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/app
      - /home/fmasiar/tester/testy:/app/testy
    environment:
      - FLASK_ENV=production
    restart: always
